os: linux
dist: xenial
language: shell

before_install:
- sudo apt-get install -y gnupg software-properties-common curl ssh unzip git
- sudo curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
- sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
- sudo apt-get update
- sudo apt-get install -y terraform
- sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
- sudo unzip awscliv2.zip
- sudo ./aws/install
- sudo curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
- sudo dpkg -i session-manager-plugin.deb
- sudo cp config /root/.ssh/

env:
  jobs:
    - TF_VAR_public_ip=<REPLACE ME> TF_VAR_region=<REPLACE ME>

jobs:
  include:
    - stage: terraform-apply
      if: branch = apply
      script: 
      - terraform init
      - terraform apply --auto-approve
      - aws s3 cp openvpn.ovpn s3://<private S3 bucket name>/
      - aws s3 cp terraform.tfstate s3://<private S3 bucket name>/
    - stage: terraform-destroy
      if: branch = destroy
      script:
      - aws s3 cp s3://<private S3 bucket name>/terraform.tfstate .
      - terraform init
      - terraform destroy --auto-approve